### ISSUE TITLE
Upwards dash cut short when jump is released

### ISSUE THREAD

**Issue by JXVD** [Juskelis/Champloo#24] opened 2016-02-01 22:01 UTC
Stand still
Hold Up
hit jump and dash at the same time
let go of both immediately

If you just dash upwards you gain more height. This occurs whenever you let go of jump during a dash.

**Comment by Juskelis** [comment] 2016-02-03 00:59
It should be fixed now. Test it, and if it is, close the issue. I don't want to close it myself in case the issue isn't actually fully solved yet

**Closed as completed** 2016-05-01 22:16 UTC
